default_language_version:
  python: python3

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2500']
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff-format
      - id: ruff

  - repo: local
    hooks:
      - id: test
        name: test
        entry: make
        args: ["test"]
        language: system
        pass_filenames: false
      - id: clean
        name: clean
        entry: make
        args: ["clean"]
        language: system
        pass_filenames: false
